controller_manager:
  ros__parameters:
    update_rate: 50
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.375
    wheel_radius: 0.14

    use_stamped_vel: false

    # open_loop: false    

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: true
    linear.x.max_velocity: 1.0  # m/s
    # linear.x.min_velocity: NAN
    linear.x.max_acceleration: 0.8  # m/s^2
    # linear.x.min_acceleration: NAN
    linear.x.max_jerk: 5.0  # m/s^3
    # linear.x.min_jerk: NAN

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: true
    angular.z.max_velocity: 1.7  # rad/s
    # angular.z.min_velocity: NAN
    angular.z.max_acceleration: 1.5  # rad/s^2
    # angular.z.min_acceleration: NAN
    angular.z.max_jerk: 2.5  # rad/s^3
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters: